### ISSUE TITLE
HttpProvider.SendAsync throws NullReferenceException

### ISSUE THREAD

**Issue by jnm2** [microsoftgraph/msgraph-sdk-dotnet-core#113]
HttpProvider.SendAsync is throwing NullReference exception during my calls to ChunkedUploadProvider.UpdateSessionStatusAsync().

This code is not designed to make sense but rather to repro the bug. It repros the first time on every try. When I try to simplify to get a self-contained repro, it gets very unreliable, so I'm not sure what to do. Anyway, let's start with this:

```cs
var provider = new ChunkedUploadProvider(session, client, fileStream, maxChunkSize: 320 * 1024);

var exceptions = new List<Exception>();

var uploadRequests = provider.GetUploadChunkRequests().ToList();

foreach (var request in uploadRequests)
{
    // Does not throw
    await provider.GetChunkRequestResponseAsync(request, exceptions);
}

// Throws NullReferenceException
await provider.UpdateSessionStatusAsync();
```

When this happens, the last Fiddler entry is always 400 bad request with the message `Upload session not found`, as I would expect from the code snippet. However, NullReferenceException should never be thrown by library code.

Request:

```
GET https://api.onedrive.com/rup/REDACTED HTTP/1.1
Host: api.onedrive.com
SdkVersion: Graph-dotnet-1.20.1
FeatureFlag: 0000004F
Cache-Control: no-store, no-cache
Authorization: bearer REDACTED
Accept-Encoding: gzip
```

Response (decoding gzip; the WWW-Authenticate header always looks like this, even for success):

```
HTTP/1.1 400 Bad Request
Content-Length: 116
Content-Type: application/json; charset=utf-8
P3P: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
WWW-Authenticate: Bearer realm="OneDriveAPI", error="invalid_token", error_description="Invalid auth token"
X-MSNSERVER: CH1AAPCB3AFC196
Strict-Transport-Security: max-age=31536000; includeSubDomains
MS-CV: SSK1WrX0H06qhBiaoD4WQA.0
X-QosStats: {"ApiId":0,"ResultType":2,"SourcePropertyId":0,"TargetPropertyId":42}
X-ThrowSite: 48e2.6f57
X-AsmVersion: UNKNOWN; 19.454.417.2005
X-MSEdge-Ref: Ref A: DFDD1D72606641D394FCE045D4E7CB6C Ref B: ASHEDGE0713 Ref C: 2020-04-27T01:22:34Z
Date: Mon, 27 Apr 2020 01:22:34 GMT

{"error":{"code":"itemNotFound","message":"Upload session not found","innererror":{"code":"uploadSessionNotFound"}}}
```

Stack trace:

```
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.UploadSessionRequest.<GetAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.ChunkedUploadProvider.<UpdateSessionStatusAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

Visual Studio's "Go To Disassembly" option seems to think the problem is in here somewhere, though because it's decompiled code I'm not sure how reliable it is:

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/590dc4d82571de160cf87b81cb15b6cf3c357db9/src/Microsoft.Graph.Core/Requests/HttpProvider.cs#L216

![image](https://user-images.githubusercontent.com/8040367/80325496-63de1680-8803-11ea-870c-0c5eeb6652b2.png) 
[AB#6420](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6420)

**Comment by jnm2** [comment]
I cloned this repository locally and was able to demonstrate that the NullReferenceException is indeed caused by accessing Headers.ContentType.MediaType while Headers.ContentType is null:

![image](https://user-images.githubusercontent.com/8040367/80326584-49a63780-8807-11ea-9605-bcb10669d403.png)

**Comment by jnm2** [comment]
Just hit the same NRE inside HttpProvider.SendAsync but this time through ChunkedUploadProvider.GetChunkRequestResponseAsync, and this time through code that makes sense as far as I know.

The NullReferenceException masks the actual error, so the only way for me to know what's happening and whether I should retry is to run Fiddler for now.

```cs
var provider = new ChunkedUploadProvider(session, client, fileStream, maxChunkSize: 320 * 1024);
var success = false;
try
{
    while (true)
    {
        var uploadRequests = provider.GetUploadChunkRequests().ToList();

        foreach (var request in uploadRequests)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var result = await provider.GetChunkRequestResponseAsync(request, exceptions);

            if (result.UploadSucceeded)
                success = true;
        }

        if (success) break;

        cancellationToken.ThrowIfCancellationRequested();
        await provider.UpdateSessionStatusAsync();
    }
}
finally
{
    if (!success) await provider.DeleteSession();
}
```

**Comment by jnm2** [comment]
ChunkedUploadProvider.DeleteSession is doing it too in the same cases where GetChunkRequestResponseAsync did it.

**Comment by Mogikan** [comment]
I have the same problem when I read file content from OneDrive and it does not exist. Instead of ServiceException I get NullReference exception which is not acceptable! I downloaded your code from github and the problem appeared at the same line as OP said:
![image](https://user-images.githubusercontent.com/5044182/80686317-bfa1eb80-8af2-11ea-84ef-b6b280b9e209.png)
I use the following code to access file:
```
 _api.Drive
                .Root
                .ItemWithPath(/*"/" + */path)
                .Content
                .Request()
                .GetAsync()
```
It calls the following method from GraphCore BaseRequest class:
       ```
 public async Task<Stream> SendStreamRequestAsync(
            object serializableObject,
            CancellationToken cancellationToken,
            HttpCompletionOption completionOption = HttpCompletionOption.ResponseContentRead)
        {
            var response = await this.SendRequestAsync(serializableObject, cancellationToken, completionOption).ConfigureAwait(false);
            return await response.Content.ReadAsStreamAsync().ConfigureAwait(false);
        }
```
Which calls the following method in BaseRequest
```
        public async Task<HttpResponseMessage> SendRequestAsync(
            object serializableObject,
            CancellationToken cancellationToken,
            HttpCompletionOption completionOption = HttpCompletionOption.ResponseContentRead)
        {
```
And SendAsync of HttpProvider fails with NullReference:
```
public async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            HttpCompletionOption completionOption,
            CancellationToken cancellationToken)
        {
```
Author of the Bug @MIchaelMainer. Commit 
Michael Mainer <MIchaelMainer@users.noreply.github.com>
Improve ServiceException/Error class information (#37)
10/1/2019 10:19:05 AM
How to fix it. Add Null check for contentType:
```
if (response.Content?.Headers.ContentType?.MediaType == "application/json")
                    {
                        string rawResponseBody = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

                        throw new ServiceException(error,
                                                   response.Headers,
                                                   response.StatusCode,
                                                   rawResponseBody);
                    }
                    else
                    {
                        // Pass through the response headers and status code to the ServiceException.
                        // System.Net.HttpStatusCode does not support RFC 6585, Additional HTTP Status Codes.
                        // Throttling status code 429 is in RFC 6586. The status code 429 will be passed through.
                        throw new ServiceException(error, response.Headers, response.StatusCode);
                    }
```
