### ISSUE TITLE
MS Graph Request Timeout Querying Azure Active Directory Service

### ISSUE THREAD

**Issue by mrranknullity** [microsoftgraph/msgraph-sdk-dotnet-core#192]
A large environment with many thousands of user and group objects.
Timeouts happen after about 30 minutes of consistent querying using delta queries with $expand criteria for user manager, group members and group owners.
Objects are requested and read in pages.
Timeouts also occur when looking up user objects by object id expanding the "manager" field.
Some timeout happen after about 30 minutes of waiting, others, after over 14 hours.
Timeout querying groups (took over 14 hours to get this error after sending the request query):

Microsoft.Graph.ServiceException: Code: timeout Message: The request timed out.
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.d__19.MoveNext()
--- End of inner exception stack trace ---
at Microsoft.Graph.HttpProvider.d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.BaseRequest.d__35.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.BaseRequest.d__31`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.GroupDeltaRequest.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Timeout querying a user by object id (took about 30 minutes to get this timeout):

System.AggregateException: One or more errors occurred.
---> Microsoft.Graph.ServiceException: Code: timeout Message: The request timed out.
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.d__19.MoveNext()
--- End of inner exception stack trace ---
at Microsoft.Graph.HttpProvider.d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.BaseRequest.d__35.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.BaseRequest.d__31`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.UserRequest.d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

### Expected behavior

If it is throttling-related, then return 429 error.
No server end timeouts if possible if application is within throttling limits

### Actual behavior

Timeouts occur  in the range of 30 minutes to over 14 hours

### Steps to reproduce the behavior
1. Create a delta query for users and groups targeting a large environment with many thousands of users and groups with hundreds of members. Expand managers for users. Expand owners and members for groups.
2. Start executing the delta queries using paging to go over the results.
3. After about 30 minutes of consistent querying, see the above timeout message.

**Comment by maisarissi** [comment]
Hi @mrranknullity .

The SDK is a wrapper for the Microsoft Graph API. The error code, throttling and timeouts are returned by the API.
Could you please check and let us know if this is still happening in the latest version of the SDK?

Unfortunately, we in the Microsoft Graph SDK team do not have any ownership of the APIs that are causing you issue.
