### ISSUE TITLE
System.InvalidOperationException in RedirectHandler.SendAsync when Microsoft Graph redirects to a relative URI

### ISSUE THREAD

**Issue by AlexandreArpin** [microsoftgraph/msgraph-sdk-dotnet-core#214]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
When Microsoft Graph's redirects to a relative URI, the SDK should follow that redirect.

If that redirect happens to be a Relative URI, the same host of the previous request should be used.

### Actual behavior
When receiving a Http Redirect with a relative URI such as `Location: /me/drive`, we get the following stack trace

```
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_Host()
   at Microsoft.Graph.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Graph.RetryHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at Microsoft.Graph.CompressionHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.SiteRequest.GetAsync(CancellationToken cancellationToken)
```

### Steps to reproduce the behavior

I currently do not have a locally reproduceable scenario but it's happening frequently enough in my live environment that I feel it warrants opening an issue.

A quick peak at `RedirectHandler.SendAsync` shows that we indeed assume the Location header will always contain an absolute URI[ but a relative URI is a valid Location as well](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location).

```
// Set newRequestUri from response
newRequest.RequestUri = response.Headers.Location;

// Remove Auth if http request's scheme or host changes
if (String.CompareOrdinal(newRequest.RequestUri.Host, request.RequestUri.Host) != 0 ||
    String.CompareOrdinal(newRequest.RequestUri.Scheme, request.RequestUri.Scheme) != 0)
{
    newRequest.Headers.Authorization = null;
}
```

I'd be very happy to open a PR with a fix if the maintainers of this repository agrees that it's not working as intended and that it should be addressed. 
[AB#8283](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8283)

**Comment by AlexandreArpin** [comment]
Thank you for triaging the issue.

Would you be open to accept contribution for this bug? We're currently waiting for a fix and do not have any workaround for this issue at the moment.

I could take a shot at fixing the issue if no one on the MS Team plans on addressing this bug soon.

**Comment by andrueastman** [comment]
@AlexandreArpin We are always happy to accept contributions. 😄

**Comment by AlexandreArpin** [comment]
@andrueastman 🎉 
I gave it a try, I'd be really happy to get your input on the PR I submitted

**Comment by andrueastman** [comment]
@AlexandreArpin Thanks so much for your PR. I have merged in and you can pull in this preview package for now and let us now if all is well as we work towards getting the minor version bump out for version 1.
https://www.nuget.org/packages/Microsoft.Graph.Core/1.25.0-preview.1

**Comment by AlexandreArpin** [comment]
@andrueastman Thank you for getting a preview package out!

After a quick deploy, I can confirm that I'm no longer seeing any System.InvalidOperationException on my production workload.

Instead, I'm seeing a JsonReaderException 😅

I figured we were probably getting some weird redirect but this probably confirms it. I have a feeling this is an issue with the Microsoft Graph itself and not the client sdk.

I'll get to work getting enough debugging information to get in touch with someone on the Microsoft Graph team. Thank you again for your support and good luck with your current projects :)
