### ISSUE TITLE
OneDrive for Business issue 

### ISSUE THREAD

**Issue by Alex0melchenko** [microsoftgraph/msgraph-sdk-dotnet-core#291]
Hello,
 
We develop a database's backups software, one of the features of which is uploading the backups to OneDrive. We can send the backups to OneDrive Personal without any issues. However, some of our customers, who send the backups to OneDrive for Business, often experience problems, despite the fact that the code for OneDrive Personal and OneDrive for Business is absolutely identical.
 
We use Microsoft.Graph and Microsoft.Graph.Core libraries to upload the file.
 
The issue happens during the files uploading in chunks.
 
Here is the stack trace of the error:

```
Failed to upload the file chunks. Delete the uploading session.|System.AggregateException: One or more errors occurred. ---> Microsoft.Graph.ServiceException: Code: generalException
Message: An error occurred sending the request.
---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
--- End of inner exception stack trace ---
at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
--- End of inner exception stack trace ---
at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
--- End of inner exception stack trace ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.RetryHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__19.MoveNext()
--- End of inner exception stack trace ---
at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.UploadChunkRequest.<SendRequestAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.UploadChunkRequest.<PutAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Graph.ChunkedUploadProvider.<GetChunkRequestResponseAsync>d__18.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Net.Pranas.SqlBak.Tools.Task.TaskTools.EvaluteResult[T](Task`1 t)
at Net.Pranas.SqlBak.Destination.OneDrive.Business.OneDriveGraphHelper.UploadFile(GraphServiceClient graphServiceClient, String remoteFolder, String remoteFileName, LocalFileInfo localFileInfo, Action`1 traceProgressAction)
```

Note: this error is not reproduced stably. Sometimes everything works correctly, and sometimes the issue happens.
 
If you need additional information, please let us know. 
[AB#10383](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10383)

**Comment by andrueastman** [comment]
Hey @Alex0melchenko, 

Thanks for raising this issue. From the stack trace it seems that you use the ChunkedUploadProvider which has since been deprecated. Ideally we now recommend using the LargeFileUploadTask. Which you can find more information about [here](https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?view=graph-rest-1.0&tabs=csharp).

Any chance you are willing to try it out and see if this will work out for you?

**Comment by Alex0melchenko** [comment]
Hi @andrueastman 

Thank you, we'll check it.

**Comment by maisarissi** [comment]
@Alex0melchenko please, reopen if you are still facing this issue.

Thank you!
