### ISSUE TITLE
No friendly error message/handling for connection failures due to proxy auth challenge

### ISSUE THREAD

**Issue by TheBluLion** [microsoftgraph/msgraph-sdk-dotnet-core#293]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
SDK provides friendly error message if proxy authentication challenge causes http request to fail and resets the connection

### Actual behavior
SDK allows for fast retries on existing connection

### Steps to reproduce the behavior
v3.35.0 graph SDK

Code: generalException
Message: Unexpected exception returned from the service.

   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at <someplace>.OnlineMeeting.UserOnlineMeeting.<CreateUserMeetingRequestAsync>d__7.MoveNext() in <somefile>.cs:line<someline>

 
[AB#10409](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10409)

**Comment by andrueastman** [comment]
Thanks for raising this issue @TheBluLion,

To help us understand the situation better, are you able to give more information on the response (e.g. status code/headers) that the comes back when this situation occurs? 
Any chance you could capture a trace on fiddler so that we may use the information to help fix this?

**Comment by andrueastman** [comment]
Closing due to inactivity for now
