### ISSUE TITLE
Fallback to http/1.1 not working in version 2.0.8 when using .net framework 4.7.2

### ISSUE THREAD

**Issue by alex3683** [microsoftgraph/msgraph-sdk-dotnet-core#400]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

Since version 2.0.8 (we used 2.0.7 before) and specifically due to commit 81f009248e57b966a656d3b2b89cdb4544feb7fb MS Graph access is no longer possible, since the http/2.0 is not working at all and the fallback to http/1.1 is not working as well. Hence I get the error message `Only HTTP/1.0 and HTTP/1.1 version requests are currently supported. Parameter name: value`. As soon as I change the version back to 1.1 after building the http request, everything works.

I created a minimal reproduction repo on github: https://github.com/alex3683/graph-http-test

Simply add the application credentials of an Azure app in the Program.cs and run the application. Api permissions should not matter, since the problem should be earlier.

When uncommenting the line `//request.Version = new Version(1, 1);` everything works.

### Expected behavior

MS Graph calls are possible with http/1.1 fallback or an option to configure the http version.

Here it states that a fallback should take place: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/commit/81f009248e57b966a656d3b2b89cdb4544feb7fb#diff-0f2277f46a926ad1c800c5e51372e0a51a78cb5b163fb09bb2a5f9ebb6fd3a19R309

### Actual behavior

Calls to MS Graph fail, since http/2 is not supported and a fallback doesn't occur.

Message (sadly in german):
```
Nur HTTP/1.0- und HTTP/1.1-Versionsanfragen werden derzeit unterstützt.
Parametername: value
```
Should be in english:
```
Only HTTP/1.0 and HTTP/1.1 version requests are currently supported. Parameter name: value
```

Stack:
```
   at System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

### Steps to reproduce the behavior

- Visual Studio 2022
- .net framework 4.7.2
- Libraries:
  - Azure.Identity 1.5.0 
  - Microsoft.Graph.Beta 4.35.0
  - Microsoft.Graph.Core 2.0.8

If you need more information, please ask.

**Comment by andrueastman** [comment]
Hey @alex3683,

Thanks for raising this. Any chance you can share the runtime information like the OS version to help us understand what would be the issue?

**Comment by alex3683** [comment]
Hi @andrueastman 

sure, no problem:
- Operating System Name: Microsoft Windows 10 Enterprise
- Version: 10.0.19044 Build 19044

**Comment by andrueastman** [comment]
Hey @alex3683,

Could you check out https://github.com/alex3683/graph-http-test/pull/1/files and see if it works for you?

I notice in your sample you are creating your own `HttpClient` which may not have the correct configurations for sending the request with the fallback.
